export const KeywordTextList = [
    { keywordText: "친절한1" },
    { keywordText: "친절한2" },
    { keywordText: "친절한3" },
    { keywordText: "친절한4" },
    { keywordText: "친절한5" },
    { keywordText: "친절한6" },
    { keywordText: "친절한7" },
    { keywordText: "친절한8" },
    { keywordText: "친절한9" },
    { keywordText: "친절한10" },
    { keywordText: "친절한11" },
    { keywordText: "친절한12" },
    { keywordText: "친절한13" },
]
